services:
  api:
    image: tliesche/powerdns-auth-proxy:develop
    hostname: powerdns-auth-proxy
    environment:
      - AUTH_TYPE=${AUTH_TYPE}
      - DB_TYPE=${DB_TYPE}
      - DB_MYSQL_HOST=${DB_MARIADB_HOST}
      - DB_MYSQL_PORT=${DB_MARIADB_PORT}
      - DB_MYSQL_USER=${DB_MARIADB_GATEWAY_USER}
      - DB_MYSQL_PASSWORD=${DB_MARIADB_GATEWAY_PASSWORD}
      - DB_MYSQL_DATABASE=${DB_MARIADB_GATEWAY_DATABASE}
      - DB_POSTGRES_HOST=${DB_POSTGRES_HOST}
      - DB_POSTGRES_PORT=${DB_POSTGRES_PORT}
      - DB_POSTGRES_USER=${DB_POSTGRES_GATEWAY_USER}
      - DB_POSTGRES_PASSWORD=${DB_POSTGRES_GATEWAY_PASSWORD}
      - DB_POSTGRES_DATABASE=${DB_POSTGRES_GATEWAY_DATABASE}
      - ENABLE_DEBUG=false
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_ISSUER=${JWT_ISSUER}
      - LOG_LEVEL=debug
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_HOST=${PDNS_HOST}
      - PDNS_PORT=${PDNS_PORT}
    volumes:
      - gateway-data:/var/lib/powerdns-auth-proxy/data
    ports:
      - "8080:8080"

  pdns-auth:
    image: pschiffe/pdns-mysql:4.9-alpine
    hostname: powerdns-auth
    environment:
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=10.5.0.0/16
      - PDNS_gmysql_host=${DB_MARIADB_HOST}
      - PDNS_gmysql_port=${DB_MARIADB_PORT}
      - PDNS_gmysql_user=${DB_MARIADB_PDNS_USER}
      - PDNS_gmysql_password=${DB_MARIADB_PDNS_PASSWORD}
      - PDNS_gmysql_dbname=${DB_MARIADB_PDNS_DATABASE}
    ports:
      - "8082:8081"

  powerdns-admin:
    image: powerdnsadmin/pda-legacy:0.4
    hostname: powerdns-admin
    environment:
      - SECRET_KEY=${POWERDNS_ADMIN_SECRET}
    volumes:
      - powerdns-admin-data:/data
    ports:
      - "8081:80"

volumes:
  gateway-data:
    driver: local
  powerdns-admin-data:
    driver: local

networks:
  default:
    external: true
    name: pdns-network
